version: '3.4'
services:
  web:
    build:
      dockerfile: Dockerfile.WEB
    ports:
      - "5000:80"
    image: "bakery-web"
  api:
    build:
      dockerfile: Dockerfile.API
    ports:
      - "6000:80"
    image: "bakery-api"
environment:
  API_URL: "https://api:80"
